### ISSUE TITLE
Problems with $.async

### ISSUE THREAD

**Issue by jbmonroe** [janelznic/simplyjs#1]
- Args to [window].setTimeout are reversed.
- obj[func] used instead of doc[func]
- I'm pretty sure the invocations of the supplied function are being invoked immediately in setTimeout, which means that those calls supply the actual callback functions.  Is that the intent?  It seems like this ought to be written with anonymous wrappers and closures on the callback functions themselves.

**Comment by janelznic** [comment]
Reversed, thanks. Closing.
